org.gradle.jvmargs=-Xmx1G

# https://fabricmc.net/develop
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.1
loader_version=0.17.2
loom_version=1.15-SNAPSHOT
fabric_api_version=0.141.3+1.21.11

mod_version=2.1
maven_group=com.arematics
archives_base_name=AdvancedChatCore

# https://jitpack.io/#sakura-ryoko/malilib
malilib_version=1.21.11-0.27.7
# https://jitpack.io/com/github/DarkKronicle/Konstruct
konstruct_version=2.0.3-build1
# https://repo.maven.apache.org/maven2/org/mariuszgromada/math/MathParser.org-mXparser
mxparser_version=4.4.2
# https://repo.maven.apache.org/maven2/io/github/maowimpl/owo
owo_version=2.0.0
# https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu
modmenu_version=15.0.0-beta.3

modrinth_slug=advancedchatcore-next
modrinth_id=iptu1EVO

# default_release_type can be stable, beta, or alpha
default_release_type=stable
project_name=AdvancedChatCore
project_url=https://modrinth.com/mod/advancedchatcore-next
project_logo=https://raw.githubusercontent.com/DarkKronicle/AdvancedChatCore/main/src/main/resources/assets/advancedchatcore/icon.png
project_color=0x134bff
changelog_hide_unimportant_commits=true
changelog_max_commit_search=200
discord_webhook_changelog_line_limit=10
